use [Interview]
CREATE TABLE #PERSON
(
     NAME        VARCHAR(60),
    GENDER    VARCHAR(1)
)  

INSERT INTO #PERSON (NAME, GENDER) VALUES ('Brijesh', 'M')
INSERT INTO #PERSON (NAME, GENDER) VALUES ('Rahul', 'M')
INSERT INTO #PERSON (NAME, GENDER) VALUES ('Saurabh', 'M')
INSERT INTO #PERSON (NAME, GENDER) VALUES ('Arti', 'F')
INSERT INTO #PERSON (NAME, GENDER) VALUES ('Jyoti', 'F')
INSERT INTO #PERSON (NAME, GENDER) VALUES ('Preeti', 'F')
 
select * from #PERSON

WITH PRS (Name, Gender, R)
AS
(
SELECT NAME, GENDER, ROW_NUMBER() OVER(PARTITION BY GENDER ORDER BY GENDER) AS R
FROM #PERSON
)
SELECT NAME, GENDER FROM PRS ORDER BY R, GENDER DESC