select GETDATE();

SELECT CURRENT_TIMESTAMP;

SELECT SYSDATETIME();

SELECT DATEPART(year, GETDATE());

SELECT YEAR(GETDATE());

SELECT month(GETDATE());

SELECT day(GETDATE());

SELECT GETUTCDATE();

SELECT DATEADD(day, 7, GETDATE())

SELECT DATEDIFF(day, '2022-01-01', '2022-01-10') AS [DateDiff]

SELECT EOMONTH(GETDATE())

SELECT FORMAT(GETDATE(), 'dd/MM/yyyy')

SELECT CONVERT(VARCHAR, GETDATE(), 120)

select SYSDATETIME()

select SYSDATETIMEOFFSET()

select SYSUTCDATETIME()

DECLARE @date DATETIME2 = '2020-06-15 21:22:11';
DECLARE @origin DATETIME2 = '2019-01-01 00:00:00';
SELECT DATE_BUCKET(WEEK, 5, @date, @origin);

SELECT DATENAME(YEAR, GETDATE())        AS 'Year';    

SELECT DATENAME(QUARTER, GETDATE())     AS 'Quarter';     

SELECT DATENAME(MONTH, GETDATE())       AS 'Month Name';  

SELECT DATENAME(DAYOFYEAR, GETDATE())   AS 'DayOfYear';   

SELECT DATENAME(DAY, GETDATE())         AS 'Day';         

SELECT DATENAME(WEEK, GETDATE())        AS 'Week';        

SELECT DATENAME(WEEKDAY, GETDATE())     AS 'Day of the Week';   

SELECT DATENAME(HOUR, GETDATE())        AS 'Hour';        

SELECT DATENAME(MINUTE, GETDATE())      AS 'Minute';     

SELECT DATENAME(SECOND, GETDATE())      AS 'Second';      

SELECT DATENAME(MILLISECOND, GETDATE()) AS 'MilliSecond'; 

SELECT DATENAME(MICROSECOND, GETDATE()) AS 'MicroSecond'; 

SELECT DATENAME(NANOSECOND, GETDATE())  AS 'NanoSecond';  

SELECT DATENAME(ISO_WEEK, GETDATE())    AS 'Week';    

SELECT ISDATE(GETDATE()) AS 'IsDate'; 

SELECT ISDATE(NULL) AS 'IsDate';