CREATE TABLE INFORMATION
( SER_NO INT IDENTITY(1,1) PRIMARY KEY,
 EMP_NAME VARCHAR(25),
 SECTION VARCHAR(20),
 CONTACT_INFO BIGINT NOT NULL,
 LOCATION VARCHAR(15)
 );

 INSERT INTO INFORMATION
 VALUES ('Vivek','MANAGER',9193458625,'GAZIABAD'),
 ('Vanya','MARKETING',7352158944,'JAMMU'),
 ('Mohit','IT',7830246946,'KANPUR'),
('Kunal','MANAGER',9635688441,'NOIDA'),
('Nishtha','SALES',9149335694,'MORADABAD'),
('Mohit','IT',7830246946,'KANPUR'),
('Jigyasa','SALES',9193458625,'GAZIABAD'),
('Vanya','MARKETING',7352158944,'JAMMU');

SELECT EMP_NAME,SECTION,CONTACT_INFO,LOCATION, COUNT(*) FROM INFORMATION
GROUP BY EMP_NAME,SECTION,CONTACT_INFO,LOCATION
HAVING COUNT(*)>1

WITH cte AS (SELECT EMP_NAME,SECTION,CONTACT_INFO,LOCATION, ROW_NUMBER() OVER (PARTITION BY EMP_NAME,SECTION,CONTACT_INFO,LOCATION ORDER BY EMP_NAME,SECTION,CONTACT_INFO,LOCATION ) rownum FROM INFORMATION )
select * from cte WHERE rownum>1;

SELECT EMP_NAME,SECTION,CONTACT_INFO,LOCATION, COUNT(*) FROM INFORMATION
GROUP BY EMP_NAME,SECTION,CONTACT_INFO,LOCATION;

WITH cte
AS (SELECT
  EMP_NAME,
  SECTION,
  CONTACT_INFO,
  LOCATION,
  ROW_NUMBER() OVER (PARTITION BY EMP_NAME, SECTION, CONTACT_INFO, LOCATION ORDER BY EMP_NAME, SECTION, CONTACT_INFO, LOCATION) rownum
FROM INFORMATION)
DELETE FROM cte
WHERE rownum > 1